name: Test Pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


env:
  FLUTTER_CHANNEL: stable


jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      VERSION_NAME: ${{ steps.set.outputs.VERSION_NAME }}
      VERSION_CODE: ${{ steps.set.outputs.VERSION_CODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from pubspec
        id: set
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //;s/+.*//')
          VERSION_CODE=${GITHUB_RUN_NUMBER}

          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

          echo "VERSION_NAME=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Show version
        run: |
          echo "VERSION_NAME: $VERSION_NAME"
          echo "VERSION_CODE: $VERSION_CODE"



  #  BUILD AND UPLOAD ANDROID (AAB)
  build_android:
    needs: [versioning]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Flutter pub get
        run: flutter pub get

      - name: Decode keystore
        run: echo "$ANDROID_KEYSTORE" | base64 --decode > android.keystore

      - name: Setup signing
        run: |
          mkdir -p android/app
          cat > android/app/key.properties <<EOF
          storePassword=${ANDROID_KEYSTORE_PASSWORD}
          keyPassword=${ANDROID_KEY_PASSWORD}
          keyAlias=${ANDROID_KEY_ALIAS}
          storeFile=../android.keystore
          EOF

      - name: Build Android AAB
        run: |
          flutter build appbundle \
            --release \
            --build-name=${{ needs.versioning.outputs.VERSION_NAME }} \
            --build-number=${{ needs.versioning.outputs.VERSION_CODE }}

      - name: Upload Android AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-aab
          path: build/app/outputs/bundle/release/*.aab


  # BUILD AND UPLOAD IOS (AdHoc)
  build_ios:
    needs: [versioning]
    runs-on: macos-latest
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Flutter pub get
        run: flutter pub get

      - name: Decode certificate & profiles
        env:
          IOS_CERT_P12: ${{ secrets.IOS_CERT_P12 }}
          IOS_PROVISION_ADHOC: ${{ secrets.IOS_PROVISION_ADHOC}}
          IOS_PROVISION_APPSTORE: ${{ secrets.IOS_PROVISION_APPSTORE}}
        run: |
          echo "$IOS_CERT_P12" | base64 --decode > build_certificate.p12
          echo "$IOS_PROVISION_ADHOC" | base64 --decode > adhoc.mobileprovision
          echo "$IOS_PROVISION_APPSTORE" | base64 --decode > appstore.mobileprovision

#############################
# Создание и настройка keychain
#############################
      - name: Create and setup keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD}}
          IOS_CERT_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD}}
        run: |
    
          KEYCHAIN_PATH="$RUNNER_TEMP/build.keychain"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          security import build_certificate.p12 -P "$IOS_CERT_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
    
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
              
          security list-keychains -d user -s "$KEYCHAIN_PATH" login.keychain
          security default-keychain -s "$KEYCHAIN_PATH"

#############################
# Добавление provisioning profiles
#############################
      - name: Install Provisioning Profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp adhoc.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          cp appstore.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
    #############################
    # Создание export_options.plist
    #############################
      - name: Create export options plist
        run: |
          cat > ios/export_options_adhoc.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
             
              <key>method</key>
              <string>ad-hoc</string>

             
              <key>signingStyle</key>
              <string>manual</string>

              <key>teamID</key>
              <string>K46L923P44</string>
             
              <key>provisioningProfiles</key>
              <dict>
               
                  <key>com.brainbit.neuro2</key>
                  <string>adhoc</string>
              </dict>

              <key>signingCertificate</key>
              <string>Apple Distribution: BRAINBIT INC. (K46L923P44)</string>
              
              <key>compileBitcode</key>
              <true/>

              
              <key>destination</key>
              <string>export</string>

              
              <key>thinning</key>
              <string>&lt;none&gt;</string>

              
              <key>stripSwiftSymbols</key>
              <true/>

              
              <key>uploadSymbols</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

      - name: Debug - Проверить сертификаты в системе
        run: |
          echo "=== Проверка всех keychain ==="
          security list-keychains
          echo "=== Поиск идентификаций ==="
          security find-identity -v -p codesigning

      - name: Build iOS AdHoc IPA
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |           
          KEYCHAIN_PATH ="$RUNNER_TEMP/build.keychain"
          
          if [ ! -f "$KEYCHAIN_PATH" ]; then
            echo "❌ ОШИБКА: Keychain не найден по пути: $KEYCHAIN_PATH"
            echo "Содержимое $RUNNER_TEMP:"
            ls -la "$RUNNER_TEMP" || true
            exit 1
          fi
          
          echo "✅ Используем keychain: $KEYCHAIN_PATH"

          
          security list-keychains -d user -s "$KEYCHAIN_PATH" login.keychain
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    

          echo "=== Проверка сертификатов в keychain ==="
          security find-identity -v -p codesigning "$KEYCHAIN_PATH"
    

          flutter build ipa \
            --release \
            --build-name=${{ needs.versioning.outputs.VERSION_NAME }} \
            --build-number=${{ needs.versioning.outputs.VERSION_CODE }} \
            --export-options-plist=ios/export_options_adhoc.plist

      - name: Upload iOS AdHoc Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-adhoc-ipa
          path: build/ios/ipa/*.ipa




